name: Code Quality

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  quality:
    name: Lint / Format / Type / Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: ESLint
        run: bun run lint
      - name: Prettier (check)
        run: bun prettier --check .
      - name: TypeScript type check
        run: bun run typecheck
      - name: Unit tests
        run: bun test
